name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature!
        Please describe your idea clearly so we can evaluate and prioritize it.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        Is your feature request related to a problem? Please describe.
        A clear description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen
      placeholder: It would be great if feedparser-rs could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered
      placeholder: I've tried... but it doesn't work because...
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Affected Platform
      description: Which platform(s) would benefit from this feature?
      multiple: true
      options:
        - Rust (feedparser-rs-core)
        - Node.js (feedparser-rs npm)
        - Python (feedparser-rs-py)
        - All platforms
    validations:
      required: true

  - type: dropdown
    id: feedparser-compat
    attributes:
      label: feedparser Compatibility
      description: Is this feature present in Python feedparser?
      options:
        - Yes, feedparser has this feature
        - No, this is a new feature
        - Not sure
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: |
        If applicable, describe or show what the API might look like
      render: rust
      placeholder: |
        // Example API usage
        let feed = parse_with_options(xml, Options {
            new_feature: true,
        })?;
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, links, or screenshots about the feature request
    validations:
      required: false
